### ISSUE TITLE
Cannot select alternate database?

### ISSUE THREAD

**Issue by kawaii** [CurtTilmes/perl6-eredis#3]
**Code:**
```raku
my $redis = Redis::Async.new('127.0.0.1:6379');
$redis.select(3);

$redis.setex($some-variable, 86400, DateTime.now);
```
**Expectation:**

When using the `.setex` method, my keys will be set in database `3`.

**Reality:**

Keys are stored in database 0.

Am I doing something wrong here? Also - is there a way for us to select the database on declaration of our `$redis` object via some additional parameter? i.e. something like `my $redis = Redis::Async.new('127.0.0.1:6379', timeout => 0, select => 3);`

**Comment by CurtTilmes** [comment]
Hmm..
Having trouble replicating.  `select` seems to work fine on my box.

Can you print the return value from the select?

```
say $redis.select(3);
```

**Comment by kawaii** [comment]
`OK`, which would indicate success, but nonetheless, keys set appear in database 0. :)

This is my main script file: https://github.com/myisha/p6-zoe-reputation/blob/master/reputation.raku

Lines L#13 and L#34 are specifically where I'm selecting the database and setting the key with expiry - is the `setex` out of scope of the `select` or something because it's taking place within the `MAIN()` function?

**Comment by CurtTilmes** [comment]
Try just a stand alone test outside your program:
```
my $redis = Redis::Async.new('127.0.0.1:6379');
say $redis.get('x');
say $redis.select(3);
say $redis.get('x');
say $redis.setex('x', 86400, DateTime.now);
say $redis.get('x');
say $redis.select(0);
say $redis.get('x');
say $redis.select(3);
say $redis.get('x');
```

I get these:
```
Nil                     # No x in database 0
OK                    # select database 3
Nil                     # No x in database 3
OK                    # in database 3, setex x
1596464332     # in database 3, get x
OK                    # select database 0
Nil                     # Still no x in database 0
OK                    # select database 3
1596464332     # in database 3, get x, still there
```

**Comment by CurtTilmes** [comment]
Redis does some caching and reuse of multiple handles.  I suspect it is using 1 handle to do your `select` and another to do your `setex`.

Try always running `select` just prior to your setex.  (You can use `:async` so any delay would be insignificant.)
```
$redis.select(3, :async);
$redis.setex($redis-key, 86400, DateTime.now, :async);
```

**Comment by CurtTilmes** [comment]
I think that is the issue.  You really only need to re-run the select (and you'll have to do it where you read too) when you might change threads.  I'm not sure how this interacts with `react`/`whenever`, but I think you could just do the `select` just inside the `whenever` (between L24/25) and it would work for you.

**Comment by kawaii** [comment]
@CurtTilmes yep, you're right, moving my `select` did indeed fix the issue, thanks for your help!
